---
name: CI

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: pytest
    runs-on: ubuntu-latest
    env:
      USING_COVERAGE: '3.8'

    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pytest-cov
          python -m pip install pylint
          
      - name: pylint ${{ matrix.python-version }}
        run: pylint tests/tests.py
      - name: unit ${{ matrix.python-version }}
        run: pytest tests/tests.py
      - name: coverage ${{ matrix.python-version }}
        run: |
          pytest --cov=./ --cov-report= tests/tests.py
          coverage report --fail-under=70
      
        
